### ISSUE TITLE
Other sct copy

### ISSUE THREAD

**Issue by norpol** [HalosGhost/colortemp#7]
Hi, I was using your `sct` version since 18th November. It works perfectly fine for me, but I just got "annoyed" not having a daemon, so suddenly [go-sct](https://github.com/d4l3k/go-sct) appeared in my search results.
It's having go as a huge dependency, which (right now) is fine for me.

Thank you so much,
norpol.

**Comment by HalosGhost** [comment]
I am sorry, I do not mean to be rude, but what are you hoping I will accomplish that would close this issue?

**Comment by norpol** [comment]
Oh, well - sorry for creating some confusion. I was just misusing the ticketing system for leaving a short "FYI" message.

**Comment by HalosGhost** [comment]
ahh, so is this just a +1 for adding the daemon functionality?

**Comment by norpol** [comment]
Kind of, yes :). I'd sure prefer to use your tidy code than "some go code with windows support".
